### PR TITLE
Add 3D touch and SFSafariViewController on iOS 9

### PR DESCRIPTION
**Pull request by MohammadAG**
Tested on an iPhone 6s (9.0.2) and an iPhone 6 (8.4.1).
Screenshot: http://i.imgur.com/UFXRg97.jpg

### CODE REVIEW

**Comment by tiferrei** [comment]
Looks cool!

**Comment by Qata** [comment]
I really like the 3D touch addition but the QR code scanner being changed to use SFSafariViewController will stop it from being able to pass back magnet links and torrents found within the page it opened, so please revert those changes.

**Comment by MohammadAG** [comment]
I've removed SFSafariViewController for all uses, it couldn't remember the password used in "Open UI" too so I guess it's not needed at all.

**Comment by tiferrei** [comment]
Hi, did you also added the Home Screen ApplicationShortcuts?

**Pull request merged**
